export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "Express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "jQuery"
  | "Batch Scripting"
  | "PowerShell"
  | "Project Management"
  | "GitHub"
  | "Documentation"
  | "Community Building"
  | "Framer Motion"
  | "C#"
  | ".NET"
  | "Android"
  | "XAML"
  | "OOP"
  | "Music Theory"
  | "Composition"
  | "Performance"
  | "Music Technology"
  | "Audio Production"
  | "Critical Listening"
  | "Big O Analysis"
  | "Problem Solving"
  | "Advanced Typing"
  | "Generics"
  | "Hooks"
  | "Component Architecture"
  | "React Router"
  | "Algorithms"
  | "Data Structures"
  | "AWS Core Services"
  | "Cloud Computing Concepts"
  | "Cloud Security"
  | "IAM"
  | "Containerization"
  | "Change Management"
  | "Amazon EC2"
  | "Amazon S3"
  | "AWS Lambda"
  | "Amazon EKS (Kubernetes)"
  | "IT Service Management"
  | "ITIL 4 Framework"
  | "Service Delivery"
  | "Incident Management"
  | "Process Improvement";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "education"
  | "contact"
  | "resume";
